'use client'

import { SavedHand } from './storage'

const now = Date.now()
const day = 24 * 60 * 60 * 1000
const hour = 60 * 60 * 1000

const t = (offset: number) => new Date(now - offset).toISOString()

export const DEMO_HANDS: SavedHand[] = [
  {
    id: 'demo-001',
    savedAt: t(2 * hour),
    imageFileName: 'session1_hand1.png',
    hand_id: '#H2401',
    blinds: '0.5/1',
    pot_size: 12.5,
    hero_cards: ['Ah', 'Ks'],
    board_cards: ['Qh', 'Jd', '9c'],
    players: [
      { position: 'BTN', stack: 100, is_hero: true },
      { position: 'BB', stack: 95, is_hero: false },
    ],
    severity: 'critical',
    headline: '리버 콜이 치명적 실수',
    mistake_summary: '오버페어 상대의 풀 사이즈 베팅에 탑페어로 콜 — 상대 레인지에서 우리가 이기는 핸드는 거의 없음',
    why_bad: ['상대 레인지가 셋·스트레이트·플러시로 가득함', '폿 오즈가 충분치 않음', '리버에서 추가로 정보 얻을 기회 없음'],
    what_to_do: '리버 풀팟 베팅엔 탑페어 폴드. 상대 레인지를 좁게 보고 EV 계산 필수',
    key_concept: '폿 오즈 계산 미숙',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 3, severity: 'good', headline: 'AKs 3-bet 표준', mistake_summary: '표준적인 프리플랍 액션', why_bad: [], what_to_do: '계속 이대로', key_concept: '프리플랍 표준 레인지' },
      { street: 'flop', hero_action: 'bet', amount: 6, severity: 'good', headline: 'C-bet 표준', mistake_summary: '드로우+오버 카드, 컨티뉴에이션 베팅 적절', why_bad: [], what_to_do: '이대로', key_concept: 'C-bet 빈도' },
      { street: 'turn', hero_action: 'call', amount: 18, severity: 'warning', headline: '턴 콜은 미묘', mistake_summary: '체크-콜 라인은 폿 컨트롤 측면에서 OK이나 디시전 트리가 좁아짐', why_bad: ['턴 카드가 상대 레인지를 강화', '레이즈 옵션이 더 나았을 수 있음'], what_to_do: '턴 레이즈로 폴드 에쿼티 확보', key_concept: 'SPR(Stack-to-Pot Ratio) 판단 미스' },
      { street: 'river', hero_action: 'call', amount: 60, severity: 'critical', headline: '리버 콜은 치명적 실수', mistake_summary: '풀팟 베팅에 탑페어로 콜 — 상대 레인지가 너무 강함', why_bad: ['폿 오즈 계산 미숙', '상대 레인지 분석 부족', '밸류 영역에서 너무 광범위하게 콜'], what_to_do: '폴드. 상대 레인지에서 우리가 이기는 핸드를 명시적으로 카운트', key_concept: '폿 오즈 계산 미숙' },
    ],
  },
  {
    id: 'demo-002',
    savedAt: t(3 * hour),
    imageFileName: 'session1_hand2.png',
    hand_id: '#H2402',
    blinds: '0.5/1',
    pot_size: 24,
    hero_cards: ['9h', '9c'],
    board_cards: ['9s', 'Kh', '2d', '5c'],
    players: [
      { position: 'CO', stack: 100, is_hero: true },
      { position: 'BTN', stack: 100, is_hero: false },
    ],
    severity: 'good',
    headline: '셋으로 올인 승리',
    mistake_summary: '완벽하게 플레이한 핸드. 프리플랍 레이즈부터 턴 올인까지, 셋을 가지고 폿을 최대한 키웠음',
    why_bad: [],
    what_to_do: '계속 이런 라인',
    key_concept: '밸류 벳, 스택 오프',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 3, severity: 'good', headline: 'CO 99 오픈 표준', mistake_summary: '포지션 활용 좋음', why_bad: [], what_to_do: '이대로', key_concept: '표준 오픈 레인지' },
      { street: 'flop', hero_action: 'bet', amount: 5, severity: 'good', headline: '셋 슬로우플레이 NO', mistake_summary: '드라이 보드에서 베팅 사이즈 적절', why_bad: [], what_to_do: '이대로', key_concept: '밸류 추출' },
      { street: 'turn', hero_action: 'all-in', amount: 88, severity: 'good', headline: '턴 올인 정확', mistake_summary: '셋으로 스택 오프 결정 완벽', why_bad: [], what_to_do: '이대로', key_concept: '밸류 벳, 스택 오프' },
    ],
  },
  {
    id: 'demo-003',
    savedAt: t(5 * hour),
    imageFileName: 'session1_hand3.png',
    hand_id: '#H2403',
    blinds: '0.5/1',
    pot_size: 8,
    hero_cards: ['Jd', 'Jc'],
    board_cards: [],
    players: [
      { position: 'MP', stack: 100, is_hero: true },
      { position: 'BTN', stack: 100, is_hero: false },
    ],
    severity: 'warning',
    headline: 'JJ 프리플랍 폴드',
    mistake_summary: '프리플랍에서 포켓 잭으로 3-벳에 폴드한 것은 너무 소극적인 플레이였음. 강한 핸드로 기회를 놓쳤음',
    why_bad: ['JJ는 4-bet 또는 콜 레인지', '상대의 3-bet 레인지를 보수적으로 가정함', '포지션 핸디캡 무시'],
    what_to_do: '4-bet bluff catcher로 콜하거나 4-bet small. 폴드는 너무 약함',
    key_concept: '오버폴드',
    decisions: [
      { street: 'preflop', hero_action: 'fold', severity: 'warning', headline: 'JJ 프리플랍 폴드', mistake_summary: '오버폴드. 3-bet 대응 레인지가 너무 좁음', why_bad: ['JJ는 콜/4-bet 레인지', '상대 3-bet 레인지 광범위'], what_to_do: 'BTN 3-bet엔 콜 또는 4-bet small', key_concept: '오버폴드' },
    ],
  },
  {
    id: 'demo-004',
    savedAt: t(8 * hour),
    imageFileName: 'session1_hand4.png',
    hand_id: '#H2404',
    blinds: '1/2',
    pot_size: 32,
    hero_cards: ['7c', '6c'],
    board_cards: ['8c', '5d', '2h', 'Qh'],
    players: [
      { position: 'BTN', stack: 60, is_hero: true },
      { position: 'BB', stack: 60, is_hero: false },
    ],
    severity: 'critical',
    headline: '턴 무리한 블러핑',
    mistake_summary: '오픈엔드 스트레이트 드로우로 턴에서 풀팟 베팅 — 상대가 강한 레인지로 콜할 가능성 높음, EV 마이너스',
    why_bad: ['턴 Q는 상대 레인지를 강화', 'fold equity가 적음', '드로우는 충분, 베팅 사이즈 과도'],
    what_to_do: '턴 체크 또는 작은 사이즈. 상대의 레인지 인식 후 진행',
    key_concept: '무리한 블러핑',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 5, severity: 'good', headline: '76s BTN 오픈', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '표준 오픈' },
      { street: 'flop', hero_action: 'bet', amount: 7, severity: 'good', headline: 'OESD C-bet', mistake_summary: '오픈엔드 스트레이트 드로우 + 백도어 플러시 드로우 — C-bet 적절', why_bad: [], what_to_do: '이대로', key_concept: 'semi-bluff 빈도' },
      { street: 'turn', hero_action: 'bet', amount: 24, severity: 'critical', headline: '턴 무리한 블러핑', mistake_summary: '풀팟 베팅은 너무 큼. fold equity 부족', why_bad: ['상대 레인지 강화됨', 'fold equity 적음', '사이징 과도'], what_to_do: '체크 또는 작은 사이즈로 컨트롤', key_concept: '무리한 블러핑' },
    ],
  },
  {
    id: 'demo-005',
    savedAt: t(1 * day),
    imageFileName: 'session2_hand1.png',
    hand_id: '#H2501',
    blinds: '1/2',
    pot_size: 16,
    hero_cards: ['Ad', 'Qd'],
    board_cards: ['Ah', '7s', '4d'],
    players: [
      { position: 'CO', stack: 200, is_hero: true },
      { position: 'BTN', stack: 200, is_hero: false },
    ],
    severity: 'warning',
    headline: '딥스택 사이징 텔',
    mistake_summary: 'AQ 탑페어로 플랍 1/3 사이즈 베팅은 폿을 너무 작게 만듦. 딥스택에선 더 큰 사이즈로 밸류 추출 필요',
    why_bad: ['딥스택 SPR이 큰데 폿이 작음', '상대 레인지에서 콜 빈도 높음', '밸류 추출 부족'],
    what_to_do: '플랍 2/3 ~ 3/4 사이즈. 턴/리버에서 큰 폿 만들기',
    key_concept: '밸류 추출 실패',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 6, severity: 'good', headline: 'CO AQs 표준', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '표준 오픈' },
      { street: 'flop', hero_action: 'bet', amount: 5, severity: 'warning', headline: '플랍 사이징 작음', mistake_summary: '딥스택에선 1/3 사이즈는 너무 작음', why_bad: ['SPR 활용 부족', '밸류 추출 약함'], what_to_do: '2/3 ~ 3/4 사이즈로 폿 빌딩', key_concept: '사이징 텔' },
    ],
  },
  {
    id: 'demo-006',
    savedAt: t(1 * day + 2 * hour),
    imageFileName: 'session2_hand2.png',
    hand_id: '#H2502',
    blinds: '1/2',
    pot_size: 28,
    hero_cards: ['Kc', 'Kh'],
    board_cards: ['8c', '7c', '6h', 'Tc'],
    players: [
      { position: 'BB', stack: 180, is_hero: true },
      { position: 'CO', stack: 180, is_hero: false },
    ],
    severity: 'critical',
    headline: '턴 보드 텍스처 무시',
    mistake_summary: 'KK로 모노톤+스트레이트 가능 보드에서 턴 큰 베팅은 위험. 보드 텍스처 변화를 간과한 액션',
    why_bad: ['턴 Tc로 플러시 완성 가능', '스트레이트 가능성 높음', '오버페어가 더 이상 베스트 핸드 아님'],
    what_to_do: '턴 체크-콜로 폿 컨트롤. 리버 폴드도 고려',
    key_concept: '보드 텍스처 변화 간과',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 8, severity: 'good', headline: 'BB KK squeeze', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '프리플랍 KK' },
      { street: 'flop', hero_action: 'bet', amount: 12, severity: 'warning', headline: '습한 보드 큰 베팅', mistake_summary: '연결된 보드에서 큰 사이즈는 미묘', why_bad: ['드로우가 콜할 빈도 높음'], what_to_do: '작은 사이즈로 폿 컨트롤', key_concept: '보드 텍스처' },
      { street: 'turn', hero_action: 'bet', amount: 28, severity: 'critical', headline: '턴 보드 텍스처 무시', mistake_summary: 'Tc로 플러시 완성 가능, 큰 베팅은 위험', why_bad: ['보드 텍스처 변화 간과', '상대 레인지 강화', 'fold equity 부족'], what_to_do: '체크-콜로 컨트롤', key_concept: '보드 텍스처 변화 간과' },
    ],
  },
  {
    id: 'demo-007',
    savedAt: t(1 * day + 5 * hour),
    imageFileName: 'session2_hand3.png',
    hand_id: '#H2503',
    blinds: '1/2',
    pot_size: 14,
    hero_cards: ['Tc', 'Td'],
    board_cards: ['As', '9h', '4c'],
    players: [
      { position: 'BTN', stack: 100, is_hero: true },
      { position: 'BB', stack: 100, is_hero: false },
    ],
    severity: 'warning',
    headline: '플랍 체크-폴드 너무 약함',
    mistake_summary: 'TT로 A 하이 플랍에서 체크-폴드는 오버폴드. 상대 레인지의 broadway가 다 A 매치는 아님',
    why_bad: ['상대 레인지에 A 빈도 약 30~40%', '백도어 드로우 무시', '폴드는 너무 약함'],
    what_to_do: '체크-콜 또는 fold equity 있는 작은 베팅',
    key_concept: '오버폴드',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 6, severity: 'good', headline: 'BTN TT 표준', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '표준 오픈' },
      { street: 'flop', hero_action: 'fold', severity: 'warning', headline: 'A 보드 오버폴드', mistake_summary: 'TT로 A 하이 보드에서 폴드는 너무 약함', why_bad: ['상대 A 빈도 30~40%', '백도어 무시'], what_to_do: '체크-콜', key_concept: '오버폴드' },
    ],
  },
  {
    id: 'demo-008',
    savedAt: t(2 * day),
    imageFileName: 'session3_hand1.png',
    hand_id: '#H2601',
    blinds: '2/5',
    pot_size: 50,
    hero_cards: ['As', 'Ks'],
    board_cards: ['Ks', '8s', '3h', '2s'],
    players: [
      { position: 'BTN', stack: 500, is_hero: true },
      { position: 'BB', stack: 500, is_hero: false },
    ],
    severity: 'good',
    headline: '딥스택 너트 플러시 드로우 활용',
    mistake_summary: '탑페어 + 너트 플러시 드로우 — 큰 SPR에서 적극적인 폿 빌딩 정확',
    why_bad: [],
    what_to_do: '계속 이런 라인',
    key_concept: '딥스택 폿 빌딩',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 15, severity: 'good', headline: 'BTN AKs 표준', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '표준 오픈' },
      { street: 'flop', hero_action: 'bet', amount: 30, severity: 'good', headline: '탑페어 + NFD', mistake_summary: '강력한 핸드, 큰 사이즈 적절', why_bad: [], what_to_do: '이대로', key_concept: '밸류 추출' },
      { street: 'turn', hero_action: 'bet', amount: 80, severity: 'good', headline: '드로우 컴플리트 시 강력', mistake_summary: '백도어 플러시 컴플리트, 적극적 폿 빌딩', why_bad: [], what_to_do: '이대로', key_concept: '딥스택 폿 빌딩' },
    ],
  },
  {
    id: 'demo-009',
    savedAt: t(2 * day + 3 * hour),
    imageFileName: 'session3_hand2.png',
    hand_id: '#H2602',
    blinds: '2/5',
    pot_size: 40,
    hero_cards: ['Qh', 'Qc'],
    board_cards: ['Jh', '8d', '5s', '7c', 'Ad'],
    players: [
      { position: 'CO', stack: 400, is_hero: true },
      { position: 'BTN', stack: 400, is_hero: false },
    ],
    severity: 'warning',
    headline: '리버 A 오버컨시더',
    mistake_summary: 'QQ로 리버 A 등장 시 너무 약하게 플레이. 상대 레인지에서 A 비율은 30% 미만',
    why_bad: ['상대 콜 레인지에 A 적음', '오버페어 가치 과소평가', '폴드 에쿼티 무시'],
    what_to_do: '리버에서 작은 밸류 베팅 시도. 상대 폴드율 측정',
    key_concept: 'SPR(Stack-to-Pot Ratio) 판단 미스',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 15, severity: 'good', headline: 'CO QQ 표준', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '표준 오픈' },
      { street: 'flop', hero_action: 'bet', amount: 20, severity: 'good', headline: '오버페어 C-bet', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: 'C-bet 빈도' },
      { street: 'turn', hero_action: 'bet', amount: 50, severity: 'good', headline: '턴 더블 배럴', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '연속 배럴' },
      { street: 'river', hero_action: 'check', severity: 'warning', headline: '리버 A 오버컨시더', mistake_summary: 'A 등장에 너무 약하게 반응', why_bad: ['상대 A 빈도 낮음', '밸류 추출 실패'], what_to_do: '작은 밸류 베팅 시도', key_concept: 'SPR(Stack-to-Pot Ratio) 판단 미스' },
    ],
  },
  {
    id: 'demo-010',
    savedAt: t(3 * day),
    imageFileName: 'session3_hand3.png',
    hand_id: '#H2603',
    blinds: '0.5/1',
    pot_size: 6,
    hero_cards: ['As', 'Js'],
    board_cards: [],
    players: [
      { position: 'UTG', stack: 100, is_hero: true },
    ],
    severity: 'critical',
    headline: 'UTG AJs 무리한 오픈',
    mistake_summary: 'UTG에서 AJs 오픈 자체는 마진이지만, 9맥스 테이블에서 너무 광범위. 포지션 활용 부족',
    why_bad: ['UTG 레인지 너무 광범위', '도미네이트당할 위험 큼', 'BTN/SB/BB 압박 받기 쉬움'],
    what_to_do: '6맥스에선 OK, 9맥스 UTG에선 폴드 또는 mix',
    key_concept: '포지션 활용 부족',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 3, severity: 'critical', headline: 'UTG AJs 광범위 오픈', mistake_summary: 'UTG 레인지 너무 광범위', why_bad: ['포지션 핸디캡', '도미네이트 위험'], what_to_do: '9맥스에선 폴드', key_concept: '포지션 활용 부족' },
    ],
  },
  {
    id: 'demo-011',
    savedAt: t(3 * day + 4 * hour),
    imageFileName: 'session4_hand1.png',
    hand_id: '#H2701',
    blinds: '1/2',
    pot_size: 10,
    hero_cards: ['5h', '5d'],
    board_cards: ['Jc', '9s', '5c'],
    players: [
      { position: 'BTN', stack: 80, is_hero: true },
      { position: 'BB', stack: 80, is_hero: false },
    ],
    severity: 'good',
    headline: '셋 마이닝 성공',
    mistake_summary: '셋이 떨어진 후 적극적인 액션으로 밸류 추출 성공',
    why_bad: [],
    what_to_do: '계속 이런 라인',
    key_concept: '셋 마이닝, 폿 컨트롤',
    decisions: [
      { street: 'preflop', hero_action: 'call', amount: 5, severity: 'good', headline: '셋 마이닝 콜', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '셋 마이닝' },
      { street: 'flop', hero_action: 'raise', amount: 12, severity: 'good', headline: '셋 체크-레이즈', mistake_summary: '드로우 많은 보드, 즉각 액션 정확', why_bad: [], what_to_do: '이대로', key_concept: '밸류 벳' },
    ],
  },
  {
    id: 'demo-012',
    savedAt: t(4 * day),
    imageFileName: 'session4_hand2.png',
    hand_id: '#H2702',
    blinds: '0.5/1',
    pot_size: 5,
    hero_cards: ['8s', '8h'],
    board_cards: ['Ah', 'Kd', 'Tc'],
    players: [
      { position: 'BTN', stack: 50, is_hero: true },
      { position: 'BB', stack: 50, is_hero: false },
    ],
    severity: 'critical',
    headline: '숏스택 88 무리한 콜',
    mistake_summary: '숏스택에서 88로 A-K-T 보드 콜은 위험. SPR 작아 폴드 결정이 더 좋음',
    why_bad: ['SPR 5 미만, 결정이 어려움', '상대 레인지 너무 강함', '백도어도 약함'],
    what_to_do: '플랍 폴드. 숏스택에선 결정 단순화',
    key_concept: 'SPR(Stack-to-Pot Ratio) 판단 미스',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 3, severity: 'good', headline: 'BTN 88 표준', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '표준 오픈' },
      { street: 'flop', hero_action: 'call', amount: 4, severity: 'critical', headline: '숏스택 SPR 무시', mistake_summary: '숏스택에서 무리한 콜', why_bad: ['SPR 작음', '상대 레인지 강함'], what_to_do: '폴드', key_concept: 'SPR(Stack-to-Pot Ratio) 판단 미스' },
    ],
  },
  {
    id: 'demo-013',
    savedAt: t(4 * day + 6 * hour),
    imageFileName: 'session4_hand3.png',
    hand_id: '#H2703',
    blinds: '1/2',
    pot_size: 20,
    hero_cards: ['Ac', 'Kd'],
    board_cards: ['Ad', '7c', '2h', '5s', '9d'],
    players: [
      { position: 'BB', stack: 200, is_hero: true },
      { position: 'BTN', stack: 200, is_hero: false },
    ],
    severity: 'warning',
    headline: '리버 밸류 추출 실패',
    mistake_summary: 'AK 탑페어 탑킥, 리버 체크-체크는 밸류 추출 실패. 상대 약한 레인지에서 밸류 베팅 가능',
    why_bad: ['상대 약한 A·미들페어 콜 빈도 있음', '리버 체크는 너무 보수적'],
    what_to_do: '리버 작은 사이즈 밸류 베팅. 상대 콜 레인지 확인',
    key_concept: '밸류 추출 실패',
    decisions: [
      { street: 'preflop', hero_action: 'call', amount: 6, severity: 'good', headline: 'BB AK 콜', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '프리플랍 디펜스' },
      { street: 'flop', hero_action: 'check', severity: 'good', headline: '체크-콜 라인', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '체크-콜' },
      { street: 'river', hero_action: 'check', severity: 'warning', headline: '리버 밸류 미스', mistake_summary: '체크-체크는 밸류 추출 실패', why_bad: ['상대 약한 콜 레인지 무시'], what_to_do: '1/3 사이즈 밸류 베팅', key_concept: '밸류 추출 실패' },
    ],
  },
  {
    id: 'demo-014',
    savedAt: t(5 * day),
    imageFileName: 'session5_hand1.png',
    hand_id: '#H2801',
    blinds: '0.25/0.5',
    pot_size: 4,
    hero_cards: ['Kh', 'Qh'],
    board_cards: ['Jh', 'Th', '4d'],
    players: [
      { position: 'CO', stack: 50, is_hero: true },
      { position: 'BB', stack: 50, is_hero: false },
    ],
    severity: 'good',
    headline: '콤보 드로우 적극 플레이',
    mistake_summary: '플러시 + 오픈엔드 스트레이트 콤보 드로우 — 적극적 액션 정확',
    why_bad: [],
    what_to_do: '계속 이런 라인',
    key_concept: '에쿼티 계산, 콤보 드로우',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 1.5, severity: 'good', headline: 'CO KQs 표준', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '표준 오픈' },
      { street: 'flop', hero_action: 'raise', amount: 8, severity: 'good', headline: '체크-레이즈 정확', mistake_summary: '콤보 드로우, 적극 플레이', why_bad: [], what_to_do: '이대로', key_concept: '콤보 드로우' },
    ],
  },
  {
    id: 'demo-015',
    savedAt: t(5 * day + 8 * hour),
    imageFileName: 'session5_hand2.png',
    hand_id: '#H2802',
    blinds: '1/2',
    pot_size: 30,
    hero_cards: ['Qd', 'Qs'],
    board_cards: ['Js', '7d', '2c'],
    players: [
      { position: 'BB', stack: 150, is_hero: true },
      { position: 'CO', stack: 150, is_hero: false },
    ],
    severity: 'warning',
    headline: '플랍 사이징 텔',
    mistake_summary: 'QQ 오버페어로 플랍 1/4 사이즈 베팅은 사이징 텔. 상대가 우리 핸드 강도를 읽기 쉬움',
    why_bad: ['약한 핸드만 큰 사이즈, 강한 핸드 작은 사이즈는 텔', '상대가 적응하면 EV 손실'],
    what_to_do: '같은 보드에선 일관된 사이징. 1/2 ~ 2/3로 통일',
    key_concept: '사이징 텔',
    decisions: [
      { street: 'preflop', hero_action: 'raise', amount: 8, severity: 'good', headline: 'BB QQ 3-bet', mistake_summary: '표준', why_bad: [], what_to_do: '이대로', key_concept: '프리플랍 QQ' },
      { street: 'flop', hero_action: 'bet', amount: 7, severity: 'warning', headline: '사이징 텔', mistake_summary: '강한 핸드 작은 사이즈는 텔', why_bad: ['일관성 부족', '상대가 적응 가능'], what_to_do: '일관된 사이징', key_concept: '사이징 텔' },
    ],
  },
]
